# Generated by Django 3.1.5 on 2021-02-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Descr',
            field=models.TextField(default=''),
        ),
    ]
